### ISSUE TITLE
emotion部分

### ISSUE THREAD

**Issue by BarryZM** [Tsunamicloud/Emotion_Bert_VITS2#1]
您好，请问缝合emotion的部分在哪个代码里哇？还有就是，train.list是怎么生成的哇。
感谢大佬！

**Comment by Tsunamicloud** [comment]
你好，这个项目主要是用来给毕设做参考用的，仅仅拉了个框架跑通了原repo的代码，Emotion部分暂未实现，思路你可以参考https://github.com/audeering/w2v2-how-to

train.list以及val.list由preprocess_text.py生成，你可以参考

**Comment by BarryZM** [comment]
好的，多谢

**Comment by oxyhexagen** [comment]
> 你好，这个项目主要是用来给毕设做参考用的，仅仅拉了个框架跑通了原repo的代码，Emotion部分暂未实现，思路你可以参考https://github.com/audeering/w2v2-how-to
> 
> train.list以及val.list由preprocess_text.py生成，你可以参考

感谢您的推荐，不知道您是否能进一步分享下预期路线，对于我这个几个小问题，w2v2最后输出的是vad和特征那么，
1.您是打算像原项目在训练时把文本bert特征插进网络一样将音频提取的情感vad或者特征插(concat)进去吗？还是要把vad三个值转换成具体的情感(anger,fear，...)之类再编码输入？
2.如果1成立的话，tts推理时候怎么输入情感信息？用另外的text2emotion模块获取还是调用者要手工输入一个具体的情感(比如w2v2里7种之一)。
3.如果目标语言不是英文的话，需要在中文数据集上重新微调一个w2v2这样的情感提取吗？
我是外行，问题可能很混乱，感谢您回复。
